name: app_walisantri
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.1.0
  flutter_native_splash: ^2.2.16
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.1
  intl: ^0.20.2
  webview_flutter: ^4.0.4
  device_info_plus: ^11.2.2
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  flutter_html: ^3.0.0-alpha.6
  url_launcher: ^6.1.11
  path_provider: ^2.0.11  # Untuk mengakses direktori penyimpanan
  pdf: ^3.10.4           # Untuk membuat file PDF
  share_plus: ^7.0.2     # Untuk berbagi file
  file_picker: ^9.2.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/logoapss.png
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoapss.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logoapss.png
    - assets/icon/logoaula.png
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Bold.ttf

  fonts:
    - family: LPMQ IsepMisbah  # Perhatikan indentasi 2 spasi
      fonts:
        - asset: assets/fonts/LPMQ IsepMisbah.ttf  # Indentasi 4 spasi
    - family: Poppins  # Indentasi 2 spasi
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf  # Indentasi 4 spasi
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
